In [65]:
#importer le cif et les packages utiles
import numpy
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.core.operations import SymmOp
from pymatgen.ext.matproj import MPRester
from pymatgen.io.cif import CifWriter
with MPRester("im80MbCif8QDmhc2y") as m:
    structure = m.get_structure_by_material_id("mp-38011")
    w = CifWriter(structure)
    w.write_file('KHS_mp-38011_symmetrized')

In [94]:
Sg = SpacegroupAnalyzer(structure)
struct2 = Sg.get_primitive_standard_structure()
Sgnew = SpacegroupAnalyzer(struct2)



Hpos = structure.sites[0].coords
Kpos = structure.sites[1].coords
Spos = structure.sites[2].coords

print('Position initiale de l\'atome H :')
print(Hpos)
print('\n Position initiale de l\'atome K :')
print(Kpos)
print('\n Position initiale de l\'atome s :')
print(Spos)

Position initiale de l'atome H :
[4.75035057 3.26886028 2.49641778]

 Position initiale de l'atome K :
[0.00787482 0.0054189  0.0041384 ]

 Position initiale de l'atome s :
[3.72803128 2.56537138 1.95916564]


In [92]:
symetries = Sgnew.get_symmetry_operations()[1:4:1]


rot0 = symetries[0].rotation_matrix
rot1 = symetries[1].rotation_matrix
rot2 = symetries[2].rotation_matrix

vect0 = symetries[0].translation_vector
vect1 = symetries[1].translation_vector
vect2 = symetries[2].translation_vector

Knew = symetries[0].operate(Kpos)
Hnew = symetries[1].operate(Hpos)
Snew = symetries[2].operate(Spos)




print('Symétrie 1 : ')
print(' \n Matrice de rotation :')
print(rot0)
print('\n Vecteur de translation : ')
print(vect0)
print('\n Equation pour la nouvelle position de l\'atome K :')
print(rot0, '*',Kpos,'+',vect0,'=',Knew)



print('\n\n Symétrie 2 : ')
print(' \n Matrice de rotation :')
print(rot1)
print('\n Vecteur de translation : ')
print(vect1)
print('\n Equation pour la nouvelle position de l\'atome H :')
print(rot1, '*',Hpos,'+',vect1,'=',Hnew)



print('\n\n Symétrie 3 : ')
print(' \n Matrice de rotation :')
print(rot2)
print('\n Vecteur de translation : ')
print(vect2)
print('\n Equation pour la nouvelle position de l\'atome S :')
print(rot2, '*',Spos,'+',vect2,'=',Snew)






Symétrie 1 : 
 
 Matrice de rotation :
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

 Vecteur de translation : 
[0. 0. 0.]

 Equation pour la nouvelle position de l'atome K :
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] * [0.00787482 0.0054189  0.0041384 ] + [0. 0. 0.] = [0.0054189  0.0041384  0.00787482]


 Symétrie 2 : 
 
 Matrice de rotation :
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]

 Vecteur de translation : 
[0. 0. 0.]

 Equation pour la nouvelle position de l'atome H :
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]] * [4.75035057 3.26886028 2.49641778] + [0. 0. 0.] = [2.49641778 4.75035057 3.26886028]


 Symétrie 3 : 
 
 Matrice de rotation :
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

 Vecteur de translation : 
[0. 0. 0.]

 Equation pour la nouvelle position de l'atome S :
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]] * [3.72803128 2.56537138 1.95916564] + [0. 0. 0.] = [3.72803128 1.95916564 2.56537138]
